os: Visual Studio 2017 Preview

version: 1.0.4.{build}

configuration:
- Debug
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe'
- cmd: dotnet-dev-win-x64.latest.exe /quiet

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- appveyor-retry dotnet restore -v Minimal
- msbuild Portable.ConcurrentDictionary.sln /p:Configuration=%CONFIGURATION% /p:VersionSuffix=%LABEL%

artifacts:
- path: Release\**\*.nupkg

cache:
- '%USERPROFILE%\.nuget\packages'