os: Visual Studio 2015

version: 1.0.2.{build}

configuration:
- Debug
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe'
- cmd: dotnet-dev-win-x64.latest.exe /quiet

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- appveyor-retry dotnet restore src\Portable.ConcurrentDictionary -v Minimal

- dotnet build src\Portable.ConcurrentDictionary\project.json -c %CONFIGURATION%
- cmd: msbuild src\Portable.ConcurrentDictionary.SL50\Portable.ConcurrentDictionary.SL50.csproj /p:Configuration=%CONFIGURATION% /p:Platform=AnyCPU
- cmd: msbuild src\Portable.ConcurrentDictionary.WP80\Portable.ConcurrentDictionary.WP80.csproj /p:Configuration=%CONFIGURATION% /p:Platform=AnyCPU
- cmd: msbuild src\Portable.ConcurrentDictionary.WP81\Portable.ConcurrentDictionary.WP81.csproj /p:Configuration=%CONFIGURATION% /p:Platform=AnyCPU

- dotnet pack -c Release --no-build --version-suffix %LABEL% -o .\artifacts .\src\Portable.ConcurrentDictionary\project.json

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'